
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      
      <div className="flex">
    
        <div className="flex-grow p-5">
          {children}
        </div>
      </div>
    </div>
  );
}